[build]
  command = "npm run generate"
  publish = ".output/public"

[dev]
  command = "npm run dev"
  port = 3000
  publish = ".output/public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
